### PR TITLE
Initial pr

### PR DESCRIPTION
**Pull request by ariperez**

### CODE REVIEW

**Comment by ariperez** [comment]
**cdk diff PD-Test-Cognition--Relays** 
```

```

**Comment by ariperez** [comment]
**cdk diff pd_halasystems_com** 
```
Stack PdHalasystemsComStack
Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment
```

**Comment by ahasna** [comment]
**cdk diff pd_halasystems_com** 
```
Stack PdHalasystemsComStack
There were no differences
```

**Comment by ahasna** [comment]
**cdk diff pd_halasystems_com** 
```
Stack PdHalasystemsComStack
Parameters
[+] Parameter GithubToken.Parameter GithubTokenParameter: {"Type":"AWS::SSM::Parameter::Value<String>","Default":"GITHUB_TOKEN"}

Resources
[+] AWS::Amplify::App HalaSystemsApp HalaSystemsApp 
[+] AWS::Amplify::Branch MasterBranch MasterBranch 
```

**Comment by ahasna** [comment]
**cdk diff pd_halasystems_com** 
```
Stack PdHalasystemsComStack
Parameters
[+] Parameter GithubToken.Parameter GithubTokenParameter: {"Type":"AWS::SSM::Parameter::Value<String>","Default":"GITHUB_TOKEN"}

Resources
[+] AWS::Amplify::App HalaSystemsApp HalaSystemsApp 
[+] AWS::Amplify::Branch MasterBranch MasterBranch 
```

**Pull request merged**
